all:
  children:
    managers:
      hosts:
        swarm-manager:

    workers:
      hosts:
        swarm-worker:

    # load-balancer:
    #   hosts:
    #     nginx-lb:

  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'