all:
  children:
    hosts:
      managers:
        swarm-manager:

    hosts:
      workers:
        swarm-worker1:

    hosts:
      load-balancer:
        nginx-lb:

  vars:
    ansible_user: clril
    ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'