- hosts: managers
  become: true
  roles: 
  - docker
  - swarm-manager
- hosts: workers
  become: true
  roles:
  - docker
  - swarm-worker1
  - swarm-worker2
- hosts: load-balancer
  become: true
  roles:
  - nginx-lb