- hosts: managers
  become: true
  roles: 
  - install-docker
  - swarm-init

- hosts: workers
  become: true
  roles:
  - install-docker
  - add-worker

- hosts: load-balancer
  become: true
  roles:
  - install-nginx