---
# tasks file for install-docker
- name: Install Dependencies
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3
    - python3-pip


- name: Install Docker Script
  shell:
    cmd: curl https://get.docker.com | bash
  become: yes


- name: Add User
  user:
    name: clril
    groups: docker
    append: yes


- name: Install Docker-Compose
  get_url: 
    url : "https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'