---
# tasks file for add-worker
- name: Install Dependencies
  pip: 
    name: docker-py


- name: Add Worker
  docker_swarm:
    state: join
    advertise_addr: swarm-worker
    join_token: "{{ hostvars['swarm-manager']['info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'swarm-manager:2377' ]